import "./globals.css";
import '@rainbow-me/rainbowkit/styles.css';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Web3Providers from "./components/Web3Providers";
import Wrap from "./components/Wrap";
import { ConnectButton } from "@rainbow-me/rainbowkit";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Eth Wrapper",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <head>
        <title>Eth Wrapper</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Web3Providers>
        <div className="flex flex-col h-screen bg-neutral-900">
          <div className="flex justify-end bg-neutral-900 p-5">
            <ConnectButton />
          </div>
          <Wrap />
        </div>
        </Web3Providers>
      </body>
    </html>
  );
}
