import "./globals.css";
import '@rainbow-me/rainbowkit/styles.css';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Web3Providers from "./components/Web3Providers";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import { Toaster } from 'sonner';
import AnimatedBlob from "./components/AnimatedBlob";
import { BlobProvider } from "./contexts/BlobContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Eth Wrapper",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Eth Wrapper</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-transparent`}
      >
        <Web3Providers>
          <BlobProvider>
            <div className="fixed inset-0 -z-10">
              <AnimatedBlob />
            </div>
            <main className="flex flex-col h-screen bg-transparent">
              <div className="flex justify-end bg-transparent p-5">
                <ConnectButton />
              </div>
              {children}
            </main>
          </BlobProvider>
        </Web3Providers>
        <Toaster
          toastOptions={{
            style: {
              background: '#171717',
              color: '#fff',
              border: '2px solid #272727',
              borderRadius: '10px',
              fontFamily: 'var(--font-geist-mono)',
            },
          }}
        />
      </body>
    </html>
  );
}
